domain: openshift.api

services:
  chartVersion: 0.1.72

machinesets:
  chartVersion: 0.1.26
  enabled: true
  helmValues:
    machineset: 
      enabled: true
    machinesets:
      - name: acs
        machine_type: t3.2xlarge
 
registry:
  enabled: false

acs:
  chartVersion: 0.1.22
  enabled: true

acm:
  namespace: open-cluster-management
  chartVersion: 0.1.26
  enabled: true

keycloak:
  chartVersion: 0.1.39
  enabled: true

gatekeeper:
  chartVersion: 0.1.17
  enabled: true

gitops:
  namespace: openshift-gitops
  channel: gitops-1.11
  enabled: true
  updater:
    chartVersion: 0.1.0
    enabled: true

tekton:
  chartVersion: 0.1.66
  enabled: false

sonarqube:
  chartVersion: ~8
  enabled: true

devhub:
  chartVersion: 0.1.9
  enabled: true

rhtas:
  chartVersion: 0.1.34
  namespace: rhtas
  enabled: false

gitlab:
  namespace: gitlab-system
  chartVersion: 0.1.53
  enabled: true

external_secrets:
  enabled: true
  chartVersion: 0.1.14
  namespace: external-secrets

vault:
  chartVersion: 0.27.0
  enabled: true
