domain: openshift.api

services:
  chartVersion: 0.3.9

nfd:
  enabled: true 
  chartVersion: 0.1.3

nvidiagpu:
  enabled: true 
  chartVersion: 0.1.1

gitops:
  namespace: openshift-gitops
  channel: gitops-1.11
  enabled: true
  updater:
    chartVersion: 0.1.0
    enabled: true

external_secrets:
  enabled: true
  chartVersion: 0.1.14
  namespace: external-secrets

vault:
  chartVersion: 0.27.0
  enabled: true

tekton:
  chartVersion: 0.1.70
  enabled: true

chains:
  enabled: false

authorino:
  enabled: true
  chartVersion: 0.1.0