domain: openshift.api

services:
  chartVersion: 0.5.1

nfd:
  enabled: true 
  chartVersion: 0.1.3

nvidiagpu:
  enabled: true 
  chartVersion: 0.1.1

gitops:
  namespace: openshift-gitops
  channel: gitops-1.11
  enabled: true
  updater:
    chartVersion: 0.1.0
    enabled: true

external_secrets:
  enabled: true
  chartVersion: 0.1.30
  namespace: external-secrets
  connectors:
    chartVersion: 0.1.1
  k8sConnector:
    enabled: true

vault:
  chartVersion: 0.27.0
  enabled: true
  address: "http://vault-service.vault-server.svc.cluster.local:8200"

tekton:
  chartVersion: 0.1.71
  enabled: true

chains:
  enabled: false

authorino:
  enabled: true
  chartVersion: 0.1.0

kiali:
  enabled: true
  chartVersion: 0.1.0

tracing:
  enabled: true
  chartVersion: 0.1.0

serverless:
  enabled: true
  chartVersion: 0.1.1

servicemesh:
  enabled: true
  chartVersion: 0.1.1

rhoai:
  enabled: true
  chartVersion: 0.1.4

devhub:
  chartVersion: 0.2.0
  enabled: true

devspaces:
  chartVersion: 0.1.5
  enabled: true

gitlab:
  namespace: gitlab-system
  chartVersion: 0.2.14
  enabled: true