domain: openshift.api

services:
  chartVersion: 0.5.67

gitops:
  namespace: openshift-gitops
  channel: gitops-1.11
  enabled: true
  updater:
    chartVersion: 0.1.0
    enabled: true

acs:
  chartVersion: 0.1.21
  enabled: true

external_secrets:
  enabled: true
  chartVersion: 0.1.30
  namespace: external-secrets
  connectors:
    chartVersion: 0.1.1
  k8sConnector:
    enabled: true

vault:
  chartVersion: 0.27.0
  enabled: true
  address: "http://vault-service.vault-server.svc.cluster.local:8200"

tekton:
  chartVersion: 0.1.71
  enabled: true

chains:
  enabled: false

devhub:
  chartVersion: 0.2.26
  enabled: true

gitlab:
  namespace: gitlab-system
  chartVersion: 0.2.21
  enabled: true

quay:
  chartVersion: 0.1.9
  enabled: true

quay_bridge:
  enabled: true
  chartVersion: 0.1.4

keycloak:
  chartVersion: 0.1.63
  enabled: true
