apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: "Project that holds all system resources."
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  healthChecks:
    - group: operators.coreos.com
      kind: Subscription
      check: |
        hs = {}
        if obj.status ~= nil and obj.status.state == "UpgradePending" then
          hs.status = "Healthy"
          hs.message = "Upgrade is pending, but manual approval is required."
        else
          hs.status = "Progressing"
          hs.message = "Unknown subscription state or upgrade in progress."
        end
        return hs