domain: openshift.api

services:
  chartVersion: 0.6.11

# GitOps
gitops:
  namespace: openshift-gitops
  channel: gitops-1.11
  enabled: true
  updater:
    chartVersion: 0.1.0
    enabled: false

# Secrets Management
external_secrets:
  enabled: true
  chartVersion: 0.1.30
  namespace: external-secrets
  connectors:
    chartVersion: 0.1.6
  k8sConnector:
    enabled: true

vault:
  chartVersion: 0.27.0
  enabled: true
  address: "http://vault-service.vault-server.svc.cluster.local:8200"

# Identity Management
keycloak:
  chartVersion: 0.2.3
  enabled: true

# Artifacts
quay:
  chartVersion: 0.1.13
  enabled: false

gitlab:
  namespace: gitlab-system
  chartVersion: 0.2.46
  enabled: true
  runners: 
    enabled: false

# Message Brokers
amq:
  enabled: false
  chartVersion: 0.0.2

# AI Requirements
authorino:
  enabled: false
  chartVersion: 0.1.0

kiali:
  enabled: false
  chartVersion: 0.1.0

tracing:
  enabled: false
  chartVersion: 0.1.0

serverless:
  enabled: false
  chartVersion: 0.1.1

servicemesh:
  enabled: false
  chartVersion: 0.1.1

rhoai:
  enabled: false
  chartVersion: 0.1.5

# Developer Experience
devhub:
  chartVersion: 0.3.1
  enabled: true

devspaces:
  chartVersion: 0.1.26
  enabled: false

